project_id_lookup <- c(
  # CLM(Clear Lake),MS(Marina),HAB,BVSHORE(Big Valley shoreline sites: M1 or BVCL6),CS(Creek Sampling),SW(Storm Water)
  "M1" = "MS",
  "M2" = "MS",
  "M3" = "MS",
  "M4" = "MS",
  "HSP" = "SW",
  "BVSWD1" = "SW",
  "NBPRSC" = "SW",
  "RSTCC" = "SW",
  "BVCL1" = "SW",
  "BVRTC1" = "SW",
  "BVRTCC" = "SW",
  "BVSWDRV" = "SW",
  "BVCL2" = "CLM",	
  "BVCL3" = "CLM",	
  "BVCL5" = "CLM",	
  "BVCL6" = "CLM",	
  "BVCL11" = "CLM",	
  "BVCL12" = "CLM",	
  "BVCL13" = "CLM",	
  "BVCL14" = "CLM",	
  "BVCL15" = "CLM",	
  "BVCL16" = "CLM",	
  "BVCL17" = "CLM",	
  "BVCL18" = "CLM",	
  "BVCL19" = "CLM",	
  "BVCL20" = "CLM",
  "FC1" = "CS", 
  "FC2" = "CS",
  "FC3" = "CS",
  "MC1" = "CS",
  "MC2" = "CS",
  "TC1" = "CS",
  "AC1" = "CS",
  "AC2" = "CS",
  "AC3" = "CS",
  "AC4" = "CS",
  "MCC1" = "CS",
  "KC1" = "CS",
  "CC1" = "CS",
  "SC1" = "CS",
  "SS1" = "CS",
  "SS2" = "CS",
  "SS3" = "CS",
  "SS4" = "CS",
  "AP01" = "HAB",
  "BP" = "HAB",
  "CLOAKS01" = "HAB",
  "CLV7" = "HAB",
  "CP" = "HAB",
  "ELEM01" = "HAB",
  "GH" = "HAB",
  "HB" = "HAB",
  "JB" = "HAB",
  "KEYS01" = "HAB",
  "KEYS03" = "HAB",
  "KP01" = "HAB",
  "LC01" = "HAB",
  "LPTNT" = "HAB",
  "LS" = "HAB",
  "LS2" = "HAB",
  "LUC01" = "HAB",
  "RED01" = "HAB",
  "RODS" = "HAB",
  "SBMMEL01" = "HAB",
  "SHADY01" = "HAB",
  "UBL" = "HAB",
  "CL-1" = "HAB",
  "CL-3" = "HAB",
  "CL-4" = "HAB",
  "CL-5" = "HAB"
  )

unit_lookup <- c(
  "Temperature, water" = "deg C", 
  "Specific conductance" = "mS/cm", 
  "Resistivity" = "KOhm/cm", 
  "Salinity" = "ppt", 
  "Total dissolved solids" = "g/L", 
  "Dissolved oxygen saturation" = "%",
  "Dissolved oxygen (DO)" = "mg/L", 
  "pH" = "None", 
  "Turbidity" = "NTU")

method_lookup <- c(
  "SM9223B" = "9223-B",
  "EPA 300.0" = "300.0",
  "ELISA" = "520060",
  "QPCR" = "1611"
)
save_objects <- function() {
  save(project_id_lookup, unit_lookup,
       file="lookup_objects.rdata")
  
}

save_objects()